apiVersion: v1
kind: ConfigMap
metadata:
  name: curiosityms-configmap-ms
  namespace: curiosityevents
data:
  SPRING_DATASOURCE_HOST: "130.61.147.13" # This is the IP of the MySQL service in my oke kubernetes
  SPRING_DATASOURCE_PORT: "3306"
  SPRING_DATASOURCE_DBNAME: "curiositydb"
  #OCI_CONFIG_STREAM_ENDPOINT: "https://cell-1.streaming.eu-frankfurt-1.oci.oraclecloud.com"
  #OCI_CONFIG_STREAM_ID: "ocid1.stream.oc1.eu-frankfurt-1.amaaaaaauevftmqau7jfdmryoq7mpcaijbnmhqvuozxnx57sdcofedybfq5q"
  KAFKA_BOOTSTRAP_SERVERS: kafka-service.kafka.svc.cluster.local:9092
  KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka-service.kafka.svc.cluster.local:9092
  KAFKA_CONSUMER_BOOTSTRAP_SERVERS: kafka-service.kafka.svc.cluster.local:9092
  KAFKA_CONSUMER_GROUP_ID: myGroupCuriosity2
