apiVersion: v1
kind: Service
metadata:
  name: curiosityms-service-clusterip
  namespace: curiosityevents
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8090
  selector:
    app: curiosityms
