apiVersion: v1
kind: ConfigMap
metadata:
  name: curiosityms-configmap-ms
  namespace: curiosityevents
data:
  SPRING_DATASOURCE_HOST: "mysql-db-deployment.curiosityevents.svc.cluster.local"
  SPRING_DATASOURCE_PORT: "80"
  SPRING_DATASOURCE_DBNAME: "curiositydb"
  KAFKA_BOOTSTRAP_SERVERS: kafka-service.kafka.svc.cluster.local:9092
  KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka-service.kafka.svc.cluster.local:9092
  KAFKA_CONSUMER_BOOTSTRAP_SERVERS: kafka-service.kafka.svc.cluster.local:9092
  KAFKA_CONSUMER_GROUP_ID: myGroupCuriosity2
